# Generated by Django 5.0.3 on 2024-04-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0015_medical_record_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ImageField(null=True, upload_to='profile')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.patientreg')),
            ],
        ),
    ]
